name: Elixir CI

on: push

concurrency:
  group: ci-tests-${{ github.ref }}
  cancel-in-progress: true

env:
  ImageOS: ubuntu22

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: adjust/setup-beam@v1.17.5
      with:
        version-file: ".tool-versions"
        version-type: "strict"
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ci-${{ env.MIX_ENV }}-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('**/mix.lock') }}
    - name: Fetch dependencies
      run: mix deps.get
    - name: Compile (strict)
      run: mix compile --warnings-as-errors
    - name: Run Tests
      run: mix test
